# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cRffjvwj7hKj5gGAJIYURJDm1+Lcm95QODtS2+aVNa+LiNpLW7rtIseFH7EJLhO387fajcbbbYhjVBHgZsMWA+nfnre/FQ0aXQUOLuRvV2MLJIsuBV2xITvtUxzX6D48hxwrVqJotqrr2QgXy2BrX5h5tnWn2V6LRz4wh8mcb0KcIxC8A+SJVZF0gdpGSFdSa5C8k95xZemSk3j21Vem9m4TnmSQhQE52qgvx2QGeROW8tVTMIEvRv/nhSOVMHP5x566cZzKCfgPeVFFYzbR2a+imEYIgeVn0AvbOmD8W16RF+jrz2CocgPk775iE69w9KWc814CCSpi6yY/sb+U3yIUV1ogfvMCmEHBTmEV96KjoE4bA5/xOkgGgQ8iyDgCNV8z9euqTcOJN7riYsilFloEr2s3MkOJ4xUv5VwJlUMrXDJbZntmZ1MyuEOjPbaO5witP+bsRoAOan6CdwIOeky/qAl9gjPbQbi1L55x1GnwQ6miL93h8YfW3tfMsdAdfvwbOJw3zkXlykdgdLjiArHrS4JWrTZDY9I1GULwgUles6pFgQsmI5LEDt/uUDE2AuxvyisCPhps2Z8fcwhk7IDGTvwkA1ukp81/PRsbW+eQ3cTA1cfHivGo5Tdie09W/ABcOeq2ySc80a4g+rlcpYDq5X5vMs9dChlldx4JxYg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml