appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: cRffjvwj7hKj5gGAJIYURJDm1+Lcm95QODtS2+aVNa+LiNpLW7rtIseFH7EJLhO387fajcbbbYhjVBHgZsMWA+nfnre/FQ0aXQUOLuRvV2MLJIsuBV2xITvtUxzX6D48hxwrVqJotqrr2QgXy2BrX5h5tnWn2V6LRz4wh8mcb0KcIxC8A+SJVZF0gdpGSFdSa5C8k95xZemSk3j21Vem9m4TnmSQhQE52qgvx2QGeROW8tVTMIEvRv/nhSOVMHP5x566cZzKCfgPeVFFYzbR2a+imEYIgeVn0AvbOmD8W16RF+jrz2CocgPk775iE69w9KWc814CCSpi6yY/sb+U3yIUV1ogfvMCmEHBTmEV96KjoE4bA5/xOkgGgQ8iyDgCNV8z9euqTcOJN7riYsilFloEr2s3MkOJ4xUv5VwJlUMrXDJbZntmZ1MyuEOjPbaO5witP+bsRoAOan6CdwIOeky/qAl9gjPbQbi1L55x1GnwQ6miL93h8YfW3tfMsdAdfvwbOJw3zkXlykdgdLjiArHrS4JWrTZDY9I1GULwgUles6pFgQsmI5LEDt/uUDE2AuxvyisCPhps2Z8fcwhk7IDGTvwkA1ukp81/PRsbW+eQ3cTA1cfHivGo5Tdie09W/ABcOeq2ySc80a4g+rlcpYDq5X5vMs9dChlldx4JxYg=
